# Generated by Django 3.2.25 on 2024-05-24 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profit_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currency',
            new_name='ProfitCurrency',
        ),
    ]
