# Generated by Django 3.2.25 on 2024-05-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('buy_from', models.CharField(max_length=100)),
                ('sell_to', models.CharField(max_length=100)),
            ],
        ),
    ]
